### ISSUE TITLE
profile url

### ISSUE THREAD

**Issue by CrackerakiUA** [jaredhanson/passport-linkedin#20]
How to get information about profile url?

**Comment by accimeesterlin** [comment]
Sounds like the property you are looking is called "siteStandardProfileRequest" from the data json object. Good luck!!

**Comment by CrackerakiUA** [comment]
to be honest, i have fixed it two years ago and missed to write here.

**Comment by accimeesterlin** [comment]
Do you remember how you fixed it. Would love to see the example

**Comment by CrackerakiUA** [comment]
No, due to we have removed that social from specific project.
