### ISSUE TITLE
Session problem

### ISSUE THREAD

**Issue by igordeoliveirasa** [jaredhanson/passport-linkedin#24]
Hi, I really would like not to use session. However, I've been receiving this message: 

> OAuth authentication requires session support. Did you forget to use express-session middleware?

My code follows: 

```
passport.use(new` LocalStrategy(
    function(username, password, done) {
        var password = password ? '' + password : null;
        return User
            .findOne({username:username})
            .populate('roles')
            .then(function(user){
                if (!user) {
                    return done(null, false);
                }
                else if (user) {
                    if (!user.password && user.facebookId) {
                        return done(null, false);
                    }
                    else if (!bcrypt.compareSync(password, user.password)) {
                        return done(null, false);
                    }
                    else {
                        return done(null, user);
                    }
                }
            },function(err){
                return done(err);
            });
    }
));

```

and

```passport.authenticate('linkedin', {session: false}, function(err, user, info) {// code continues...```

**Comment by igordeoliveirasa** [comment]
passport.use(new LocalStrategy(
    function(username, password, done) {
        var password = password ? '' + password : null;
        return User
            .findOne({username:username})
            .populate('roles')
            .then(function(user){
                if (!user) {
                    return done(null, false);
                }
                else if (user) {
                    if (!user.password && user.facebookId) {
                        return done(null, false);
                    }
                    else if (!bcrypt.compareSync(password, user.password)) {
                        return done(null, false);
                    }
                    else {
                        return done(null, user);
                    }
                }
            },function(err){
                return done(err);
            });
    }
));



passport.authenticate('local', {session: false}, function(err, user, info) { // code continues...

**Comment by igordeoliveirasa** [comment]
Don't worry! My fault!

**Comment by samcus** [comment]
@igordeoliveirasa I added '{session: false}' and I still get the error about session being required, any ideas?

**Comment by samcus** [comment]
@igordeoliveirasa I ended up using https://github.com/auth0/passport-linkedin-oauth2 instead.
