### ISSUE TITLE
stateless session

### ISSUE THREAD

**Issue by yamsellem** [jaredhanson/passport-linkedin#8]
It seems to me that some strategies provide a `stateless` option that allow to avoid the `serializeUser` call and the session save.

My needs is to connect a user with a local strategy and add accounts to this existing session. So, I need to deactivate the session round trip of other 'strategy'.

Thanks.

**Comment by samcus** [comment]
@yamsellem I added '{session: false}' and I still get the error about session being required, any ideas?

**Comment by samcus** [comment]
@yamsellem I ended up using https://github.com/auth0/passport-linkedin-oauth2 instead.
